Added category resource
labd/terraform-provider-commercetools pull request #152
Opened 2021-02-26 13:41 UTC by Ardjan-Aalberts

2021-02-26 15:34 UTC, qdegraaf requested changes

2021-02-26 15:34 UTC, qdegraaf commented on commercetools/resource_category.go
> +				Type:     schema.TypeMap,
There's a 
`const TypeLocalizedString = schema.TypeMap` 
type alias in utils.go which can be used for documentation purposes and clarity in the case of Maps which are Localized Strings. You can use that here (and for the other localized string fields).

2021-02-26 15:34 UTC, qdegraaf commented on commercetools/resource_category.go
> +	category, err := client.CategoryGetWithID(context.Background(), d.Id())
There's no need for this call. You can get the version from the state like so:
```suggestion
	version := d.Get("version").(int)
```
And use that in the `client.CategoryDeleteWithID`. Should be a bit faster

2021-02-26 15:34 UTC, qdegraaf commented on commercetools/resource_category_test.go
> +				),
For completeness' sake could you expand the checks to include all settable fields?

2021-02-26 15:34 UTC, qdegraaf commented on commercetools/resource_category_test.go
> +		}
See also comment above. It would be nice if we could test for all settable fields

2021-02-26 15:34 UTC, qdegraaf commented on docs/resource_category.md
> +Categories allow to organize products into hiearchical structures.
```suggestion
Categories allow you to organize products into hiearchical structures.
```

2021-02-26 17:19 UTC, qdegraaf approved these changes

2021-03-17 16:54 UTC, pimvernooij commented
Should assets be plural? Or does a category only have a single asset and should it be singular?

2021-03-18 09:51 UTC, Ardjan-Aalberts commented
> Should assets be plural? Or does a category only have a single asset and should it be singular?

I tested this out with the http API, which uses an array of assets. One category can have multiple assets related to that category. (https://docs.commercetools.com/api/projects/categories#categorydraft)

2021-03-19 14:38 UTC, merged

2021-03-20 15:55 UTC, pimvernooij commented
@Ardjan-Aalberts i think something went wrong with merging this PR; it does not seem to be in the master branch?

2021-03-20 19:10 UTC, qdegraaf commented
Hey @pimvernooij . The merge broke the tests. There was a bug in the functionality, potentially in the SDK as there seems to be an issue with deserializing the Category struct from the API response. I had a look with @Ardjan-Aalberts on friday but could not get to the bottom. We opted to revert the master branch to before the merge while we work on a fix, to avoid accidentally releasing broken code.