Adds category resource to the Commercetools provider
labd/terraform-provider-commercetools pull request #160
Opened 2021-04-02 16:41 UTC by Ardjan-Aalberts

Adds category resource to the provider. Hierarchy and assets are supported.

2021-04-03 06:34 UTC, viggin543 approved these changes
clean work

2021-04-03 06:34 UTC, viggin543 commented on commercetools/resource_category.go
> +			ContentType: s["content_type"].(string),
content_type and key props  are optional and might be nil ( casting nil to string will cause panic ).

I see you have a test where you create a category with an asset that has no content type .
if it works thas weird.

2021-04-03 06:34 UTC, viggin543 commented on commercetools/resource_category.go
> +			Key:         i["key"].(string),
key prop is optional

2021-04-03 06:51 UTC, viggin543 reviewed
you also don't support adding new assets ( only  update existing sources of an asset )

2021-04-07 12:24 UTC, qdegraaf requested changes
LGTM functionality wise!

Two changes I'd like to request is that we now have support for a new way of generating docs using the `Description` fields of the schema. If you could fill in these fields (see other resource for inspiration) this would save us having to fill them out down the line when we definitively move away from read the docs to the new set-up.

Second, in order to keep the tests a bit more consistent, master now has `CheckDestroy` funcs for all resources. If you could add one here as well that'd be grand.

2021-04-08 11:55 UTC, qdegraaf approved these changes

2021-04-08 12:06 UTC, Ardjan-Aalberts commented
> you also don't support adding new assets ( only update existing sources of an asset )

Hi @viggin543, creating assets is supported. The assets are added to the draft after the draft is initially created. This because we first check if the Terraform config contains assets.

Thanks for reviewing the pull request!

2021-04-08 12:06 UTC, merged