Add support for price functions on shipping zone rate tiers
labd/terraform-provider-commercetools pull request #202
Opened 2022-02-10 03:56 UTC by petehayes102

Note that when I ran `make docs`, it introduced a tonne of changes that are not related to my change. I'm happy to add the changes to this PR but wanted to confirm with the maintainers first.

2022-03-01 12:05 UTC, mvantellingen requested changes

2022-03-01 12:05 UTC, mvantellingen commented on commercetools/resource_shipping_zone_rate.go
> +		if len(priceList) > 0 {
There is a utility function available to achieve this:

`priceMap, err := elementFromSlice(priceTier, "price")`

2022-03-01 12:05 UTC, mvantellingen commented on commercetools/resource_shipping_zone_rate.go
> +			if len(functionList) > 0 {
Same as above, you can leverage `elementFromSlice()`

2022-03-01 12:07 UTC, mvantellingen commented
Looks good! Two small changes to simplify the code. Note that i'm more and more doubting if the added nesting of resources makes it better. 

So instead of 

```hcl
        shipping_rate_price_tier {
            type               = "CartScore"
            score              = 30
            price_function {
                function      = "x + 1"
                currency_code = "%[3]s"
            }
```

flatten it as 
```hcl
        shipping_rate_price_tier {
            type               = "CartScore"
            score              = 30
            price_function_expression = "x + 1"
            price_function_currency_code = "%[3]s"
}
```

But that might be food for thought for the future

2022-08-10 20:02 UTC, jpuffen commented
any update on this?

2022-08-16 11:42 UTC, mvantellingen commented
I was in the process of rebasing this but stumbled upon a question.

We now have

```hcl
  shipping_rate_price_tier {
    type  = "CartScore"
    score = 10

    price {
      cent_amount   = 5000
      currency_code = "EUR"
    }
  }
```

and for the price function you added

```hcl
  shipping_rate_price_tier {
    type  = "CartScore"
    score = 10

    price_function {
      function   = "x + 1"
      currency_code = "EUR"
    }
  }
```

Is there a reason why we don't use:


```hcl
  shipping_rate_price_tier {
    type  = "CartScore"
    score = 10

    price {
      function   = "x + 1"
      currency_code = "EUR"
    }
  }
```

2022-08-16 11:48 UTC, petehayes102 commented
Sorry for the delay here.

@jpuffen I've been pulled onto other projects and have never written Go before/since, so amending the code will take a bit of trial and error. I'll try and revisit this during the week.

@mvantellingen Yeah good question. I think I was trying to follow what I thought was the convention, but your suggestion is cleaner. Happy to bundle that in with the other changes.

2022-08-16 11:58 UTC, mvantellingen commented
Cool, i've pushed the rebase I did, you can find it here: https://github.com/labd/terraform-provider-commercetools/tree/petehayes102-shipping-rate-pricefn

2022-08-30 01:37 UTC, petehayes102 commented
@mvantellingen I just pushed the rebased changes, but it seems to have introduced a bunch of unintended changes...

2022-08-30 01:52 UTC, petehayes102 commented
Ok that's better. I rebased again from `main` and now it's back to just my changeset.

2022-09-28 10:20 UTC, merged

2022-09-29 10:50 UTC, mvantellingen commented
I've merged this but ran in a couple of issues. I think my suggestion of using a single `price` block with either `function` or `cent_amount` is not the correct one :-) since it conflicts with how commercetools behaves.

I'll fix it this week

2022-09-30 09:38 UTC, mvantellingen commented
Fixed, will be in v1.5.0

Thanks!

2022-09-30 09:42 UTC, petehayes102 commented
No dramas mate. Glad we got there in the end! :)