fix: Absolute Cart Discount Money marshaling (to list)
labd/terraform-provider-commercetools pull request #374
Opened 2023-06-14 10:36 UTC by papkos

Fixes https://github.com/labd/terraform-provider-commercetools/issues/344

2023-06-14 10:50 UTC, FluffyBucket approved these changes

2023-06-14 10:50 UTC, FluffyBucket commented on commercetools/resource_cart_discount.go
> +		manyMoney := make([]map[string]any, len(v.Money))
You did not wanted to call it `moneys`? :stuck_out_tongue:

2023-06-14 13:02 UTC, rioam2 approved these changes

2023-07-14 23:05 UTC, zackpollard commented
Hey, thanks for the work on this, any chance we can get this merged soon? :smile:

2023-08-03 09:04 UTC, valerydluski commented
Hello, could you tell me how soon this pull request is planned to be merged? We are really looking forward to this fix.

2023-08-03 10:56 UTC, demeyerthom requested changes
@papkos thanks for creating this PR!

I left some comments I hope you can look into, but overall it looks good to me!

2023-08-03 10:56 UTC, demeyerthom commented on .github/workflows/tests.yml
> +    # Don't run this for this fork
Code you please re-enable this?

2023-08-03 10:56 UTC, demeyerthom commented on commercetools/resource_cart_discount.go
> +			"permyriad": 0,
I don't think the API supports `permyriad` in this case?

2023-08-03 10:56 UTC, demeyerthom commented on commercetools/resource_cart_discount.go
> +			"permyriad": 0,
I don't think the API supports permyriad in this case?

2023-08-03 10:56 UTC, demeyerthom commented on commercetools/resource_cart_discount_absolute_test.go
> +package commercetools
Can we also add a test for the fixed discount? That way we have all cases except the `giftLineItem` covered

2023-08-08 08:56 UTC, merged

2023-08-08 08:57 UTC, demeyerthom commented
Merged this to v1.8.0 branch and will fix testing there

2023-08-08 09:10 UTC, papkos commented
> Merged this to v1.8.0 branch and will fix testing there

Thank you, and sorry for not getting back to this sooner. 
Looking forward to the new release!